
package si.durs.wsdl.loginservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ILoginService", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ILoginService {


    /**
     * 
     * @param taxPayerId
     * @param taxPayerType
     * @return
     *     returns si.durs.wsdl.loginservice.TokenResponse
     * @throws ILoginServiceLoginUsingClientCertificateBadRequestFaultFaultFaultMessage
     * @throws ILoginServiceLoginUsingClientCertificateServerErrorFaultFaultFaultMessage
     * @throws ILoginServiceLoginUsingClientCertificateUnauthorizedFaultFaultFaultMessage
     */
    @WebMethod(operationName = "LoginUsingClientCertificate", action = "http://tempuri.org/ILoginService/LoginUsingClientCertificate")
    @WebResult(name = "LoginUsingClientCertificateResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "LoginUsingClientCertificate", targetNamespace = "http://tempuri.org/", className = "si.durs.wsdl.loginservice.LoginUsingClientCertificate")
    @ResponseWrapper(localName = "LoginUsingClientCertificateResponse", targetNamespace = "http://tempuri.org/", className = "si.durs.wsdl.loginservice.LoginUsingClientCertificateResponse")
    public TokenResponse loginUsingClientCertificate(
        @WebParam(name = "taxPayerId", targetNamespace = "http://tempuri.org/")
        Integer taxPayerId,
        @WebParam(name = "taxPayerType", targetNamespace = "http://tempuri.org/")
        TaxPayerType taxPayerType)
        throws ILoginServiceLoginUsingClientCertificateBadRequestFaultFaultFaultMessage, ILoginServiceLoginUsingClientCertificateServerErrorFaultFaultFaultMessage, ILoginServiceLoginUsingClientCertificateUnauthorizedFaultFaultFaultMessage
    ;

}
