
package si.durs.wsdl.loginservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "ServerErrorFault", targetNamespace = "http://schemas.datacontract.org/2004/07/Endava.Edp.InvoiceBook.Web.Soap")
public class ILoginServiceLoginUsingClientCertificateServerErrorFaultFaultFaultMessage
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ServerErrorFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ILoginServiceLoginUsingClientCertificateServerErrorFaultFaultFaultMessage(String message, ServerErrorFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public ILoginServiceLoginUsingClientCertificateServerErrorFaultFaultFaultMessage(String message, ServerErrorFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: si.durs.wsdl.loginservice.ServerErrorFault
     */
    public ServerErrorFault getFaultInfo() {
        return faultInfo;
    }

}
